export const English = {
    ERROR_NameEmailAndPassRequired: 'Name, email and password required',
    ERROR_UserAlreadyExists: 'User already exists',
    ERROR_Unknown: 'Unknown error. Please try again soon or contact us.',
    ERROR_UserNotFound: `Sorry - that username was not found or the password is wrong`,
    ERROR_PasswordWrong: `Sorry - that username was not found or the password is wrong`,
    ERROR_ShouldLogInUsingProvider: 'Looks like that account is tied to Google - try logging in with Google.',
    ERROR_PasswordMustBeAtLeastSixCharacters: 'Password must be at least six characters',
    ERROR_InvalidEmail: 'Invalid email',
    ERROR_NoSuchFile: 'No file attachment found',
    ERROR_TeamNameRequired: 'Name required to create a new team',
    ERROR_UserDoesntHaveAccessForTeam: 'Unauthorized',
    ERROR_UserDoesntHaveAccess: 'Unauthorized',
    ERROR_TooManyInvites: 'Sorry, you have too many invites open for this team',
    ERROR_UserAlreadyInvitedToTeam: 'That email is already invited to this team',
    ERROR_MissingId: 'Missing ID',
    ERROR_MissingParameters: 'Missing Parameters',
    ERROR_MissingEmail: 'Missing email',
    ERROR_DoesntExist: 'Doesn\'t exist',
    ERROR_NoInviteFound: 'No invite found for the user for this team',
    ERROR_DoesntExistOrUnauthorized: 'Doesn\'t exist or unauthorized',
    ERROR_SearchQueryTooLong: 'Search query is too long',
    ERROR_UnknownProperty: 'Unknown property / properties: {0}',
    DEFAULTS_MyFirstPlate: 'My Plate',
    DEFAULTS_TeamFirstPlate: 'Team First Plate',
    DEFAULTS_GOALS: 'Goals',
    DEFAULTS_TASKS: 'Tasks',
    DEFAULTS_DONE: 'Done',
    DEFAULTS_PLATTER: 'Plates',
    DEFAULTS_PLATTER_NAME: 'My Plates',
    NOTIFICATION_InviteForTeam: 'You have been invited by {0} to join the team {1}!',
    NOTIFICATION_ItemDueSoon: 'You have an item due soon.'
}