---
# Backup mongo
- name: create {{ db_backup_dir }} directory
  file: path={{ db_backup_dir }} state=directory mode=0755

- name: backup mongo db
  environment: "{{ PLATE_ENVIRONMENT }}"
  shell:  mongodump --db plate -u $DB_USER -p "$DB_PASS" --gzip --archive={{ db_backup_dir }}/plate_`date "+%Y-%m-%d-%H-%M-%S"`.archive